version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
  
  # Main library
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      # Keep Kotlin on 1.9.x for compatibility
      - dependency-name: "org.jetbrains.kotlin.*"
        versions: [">=2.0.0"]
      # Keep kotlinx-serialization on 1.6.x (compatible with Kotlin 1.9.x)
      - dependency-name: "org.jetbrains.kotlinx:kotlinx-serialization-json"
        versions: [">=1.7.0"]
      # Keep Mockito on 4.x (requires JVM 1.8)
      - dependency-name: "org.mockito:*"
        versions: [">=5.0.0"]
  
  # SimpleCheckout sample
  - package-ecosystem: gradle
    directory: "/samples/SimpleCheckout"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
  
  # MobileBuyIntegration sample
  - package-ecosystem: gradle
    directory: "/samples/MobileBuyIntegration"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
