version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
  
  # Main library
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  
  # SimpleCheckout sample
  - package-ecosystem: gradle
    directory: "/samples/SimpleCheckout"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  
  # MobileBuyIntegration sample
  - package-ecosystem: gradle
    directory: "/samples/MobileBuyIntegration"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
