naming:
  EnumNaming:
    active: true
    excludes: [ '**/WebMessage.kt' ]
  FunctionNaming:
    active: true
    ignoreAnnotated: ['Composable']
style:
  FunctionOnlyReturningConstant:
    active: true
    excludes: [ '**/WebViewController.kt' ]
  MaxLineLength:
    active: true
    maxLineLength: 140
  ForbiddenComment:
    active: false
  NewLineAtEndOfFile:
    active: false
exceptions:
  TooGenericExceptionCaught:
    active: false
complexity:
  LongParameterList:
    active: true
    functionThreshold: 10
    constructorThreshold: 11
    ignoreDefaultParameters: true
  TooManyFunctions:
    thresholdInClasses: 16
