name: checkout-sheet-kit-android

type: android

up:
  - ruby
  - packages:
    - rover
  - custom:
      name: Ensure sample app .env files exists
      met?: |
        ([ -f "./samples/MobileBuyIntegration/.env" ] || exit 1)
      meet: ./scripts/setup_env.sh

commands:
  build:
    desc: Build the library
    run: ./gradlew :lib:build
    subcommands:
      samples:
        desc: Build all sample applications
        run: cd samples/MobileBuyIntegration && ./gradlew build

  test:
    subcommands:
      specific:
        desc: Run specific test class
        syntax: <TestClassName> (e.g. CheckoutBridgeTest)
        run: ./gradlew :lib:testDebugUnitTest --tests "$1"
    desc: Run all tests with clean build
    run: ./gradlew clean test --console=plain

  style:
    desc: Run code formatting and linting
    aliases: [lint]
    run: ./gradlew detekt lintRelease

  fix:
    desc: Automatically fix format and lint issues where possible
    run: ./gradlew detekt --auto-correct

  apollo:
    subcommands:
      download_schema:
        desc: "Download GraphQL Schema. Usage: dev apollo download_schema"
        run: ./scripts/apollo_download_schema
      codegen:
        desc: "Generate Apollo Kotlin models. Usage: dev apollo codegen"
        run: ./scripts/apollo_codegen

check:
  license-headers: ./scripts/check_license_headers.rb
  detekt: ./gradlew detekt
  android-lint: ./gradlew lintRelease

open:
  "GitHub": "https://github.com/Shopify/checkout-sheet-kit-android"
  "Issues": "https://github.com/Shopify/checkout-sheet-kit-android/issues"
  "PRs": "https://github.com/Shopify/checkout-sheet-kit-android/pulls"
