name: Lint & Run Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          submodules: true

      - name: Install JDK 1.17
        uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4.2.2
        with:
          distribution: zulu
          java-version: 17
          cache: 'gradle'

      - name: Run Tests
        run: ./gradlew clean test --console=plain

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          submodules: true

      - name: Install JDK 1.17
        uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4.2.2
        with:
          distribution: zulu
          java-version: 17
          cache: 'gradle'

      - name: Kotlin Lint
        run: ./gradlew detekt

      - name: Android Lint
        run: ./gradlew lintRelease
